language: perl

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y librdf-perl
install:
  - "cpanm --quiet --notest Module::Install::AuthorTests"
  - "cpanm --quiet --notest Module::Install::DOAPChangeSets"
  - "cpanm --quiet --notest Attean"
  - "cpanm --quiet --notest Test::Modern"
  - "cpanm --quiet --notest Test::Moose"
  - "cpanm --quiet --notest Test::Pod"
  - "cpanm --quiet --notest Test::Pod::Coverage"
  - "cpanm --quiet --notest Test::Roo"
  - "cpanm --quiet --notest DBI"
  - "cpanm --quiet --notest DBD::Pg"
  - "cpanm --quiet --notest DBD::mysql"
  - "cpanm --quiet --notest DBD::SQLite"
  - "cpanm --quiet --notest File::Slurp"
  - "cpanm --quiet --notest List::MoreUtils"
  - "cpanm --quiet --notest Moo"
  - "cpanm --quiet --notest MooX::Log::Any"
  - "cpanm --quiet --notest namespace::clean"
  - "cpanm --quiet --notest Type::Tiny"
  - "cpanm --quiet --notest DBIx::MultiStatementDo"
script:
  - "perl Makefile.PL && make test"
